env: 
  production: false
  version: 0.1.0
  
port: 8002

logPath: ./logs/

mysql:
  connect: false
  host: 10.1.1.128
  port: 3306
  dbname: ibp #azure 建立db一定要小寫
  user: iBPej03xu3m06 #azure mysql管理員不能有符號
  pass: P@ssw0rd23442600 # 密碼一定要有大小寫+符號數字
  migrate: true
  # 以下是用azure的設定
  azure_host: ibp-test.mysql.database.azure.com
  # Azure Database for MySQL flexible server 建立成功之後 password跟 Networking裡面的firewall rule都要重新設定，就算第一次看到有東西也要重設，不然無法連線成功
 
mongo:
  connect: true
  host: 10.1.1.128
  port: 27017
  dbname: ha_alarm
  user: iBPej03xu3m06
  pass: P@ssw0rd23442600
  azure_cosmos: mongodb://test-ibp:Jf0cM3bPR4PddV5s2IEOHDZMDE1SKh33pCe4bW8DuXYIgiw2Y8bZhME1ZFuvbolay9BDl9vMMirlnp760WTQwg==@test-ibp.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@test-ibp@

redis: 
  host: 10.1.1.128
  port: 6379
  pass: P@ssw0rd23442600

SMTP:
  host: smtp.mailtrap.io
  port: 587
  user: 9f27ce933f1d82
  pass: be7dbb10511a7f
  from: iBP@cht.com.tw
  to: cnyang@cht.com.tw 

JWT:
  secret: iBPej03xu3m06

TeamsHook:
  error: https://cht365.webhook.office.com/webhookb2/25a75eae-70e0-4e2c-8a50-61332a024613@54eb9440-cf03-45fe-835e-61bd4ce515c8/IncomingWebhook/7b70e016989b49acb0d695b7354f6d9b/9f207772-6a3a-4ee3-b964-4b2cab0d394c